import { Injectable, ConflictException } from '@nestjs/common';
import { PersonRepositoryPort } from '../../domain/ports/person.repository.port';
import { Person } from '../../domain/entities/person.entity';
import { CreatePersonDto } from '../dtos/create-person.dto';
import { PersonResponseDto } from '../dtos/person-response.dto';

@Injectable()
export class CreatePersonUseCase {
  constructor(private readonly personRepository: PersonRepositoryPort) {}

  async execute(dto: CreatePersonDto): Promise<PersonResponseDto> {
    const existing = await this.personRepository.findByDocument(dto.documentNumber);
    if (existing) {
      throw new ConflictException(
        `Ya existe una persona registrada con el documento ${dto.documentNumber} (${existing.fullName})`,
      );
    }

    const person = new Person({
      id: '', // Generated by TypeORM / UUID
      type: dto.type,
      documentType: dto.documentType,
      documentNumber: dto.documentNumber.trim(),
      firstName: dto.firstName.trim(),
      paternalSurname: dto.paternalSurname.trim(),
      maternalSurname: dto.maternalSurname?.trim() || '',
      email: dto.email?.trim() || null,
      phone: dto.phone?.trim() || null,
      address: dto.address?.trim() || null,
      position: dto.position?.trim() || null,
      office: dto.office?.trim() || null,
      laborCondition: dto.laborCondition?.trim() || null,
      entryDate: dto.entryDate || null,
      businessName: dto.businessName?.trim() || null,
      allowsOnlineAccess: dto.allowsOnlineAccess ?? (dto.type === 'ADMINISTRADO'),
      isActive: true,
    });

    const saved = await this.personRepository.save(person);
    return PersonResponseDto.fromDomain(saved);
  }
}
